name: Deploy to Preview Channel

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_preview:
    if: startsWith(github.event.pull_request.head.ref, 'feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Create Environment File for Production
        run: echo "${{ vars.ENV_PRODUCTION }}" > .env.production

      - name: Write Firebase Configuration File (firebase.json)
        run: |
          cat <<EOF > firebase.json
          ${{ vars.FIREBASE_JSON }}
          EOF

      - name: Install Dependencies and Build Project
        run: npm ci && npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 7d
          projectId: ${{ vars.PROJECT_ID }}
